### ISSUE TITLE
Missing plugin.yml

### ISSUE THREAD

**Issue by ZappySK** [Andre601/Math-Expansion#2]
Could not load 'plugins/Expansion-Math-1.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.5.jar:git-Purpur-1051]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.5.jar:git-Purpur-1051]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Purpur-1051]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:263) ~[patched_1.16.5.jar:git-Purpur-1051]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1051]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more

**Comment by Andre601** [comment]
The Math expansion is NOT a plugin. It's a PlaceholderAPI Expansion and should be used like one.
Please double-check next time before opening a redundant issue. Thanks
